### ISSUE TITLE
Violates best practises

### ISSUE THREAD

**Issue by kannes** [owenlo/RLE-Python#1]
Instead of `range(len(sequence))` you can use `enumerate(sequence)`, it is much nicer and does not smell of other languages. https://docs.python.org/3/library/functions.html#enumerate and see e.g. https://python-forum.io/Thread-Basic-Never-use-for-i-in-range-len-sequence for more motivation.

Instead of concatenating a string step by step, store the parts of it in a list and `"".join(sequence)` it later. See 6 in https://docs.python.org/3/library/stdtypes.html

Also be aware that your approach will not work if someone wants to encode a string like "1101101110000100" ;)

**Comment by owenlo** [comment]
Hello kannes, thanks for your feedback. I agree on all your points. I've updated the code to try and address the loop and string joining based on your advice.

I will aim to address the handling of binary numbers in the future when I have some more time  ;)

**Comment by kannes** [comment]
Awesome!

This repo is #1 on Google for "rle python" btw so you can shine :)

**Comment by owenlo** [comment]
I've updated the code to support encoding/decoding of both characters and digits (including binary values). Here's an example output:

Test Vector: 1111111111199999999333333330000000
Encoded Result: 111898370
Decoded Result: 1111111111199999999333333330000000

Once again, thank you for your contributions :)

**Comment by kannes** [comment]
Awesome!
